WIP: adding update graph documentation
operator-framework/olm-docs pull request #86
Opened 2020-12-09 23:29 UTC by gallettilance

2020-12-10 21:42 UTC, exdx commented
/lgtm

2020-12-10 21:45 UTC, ankitathomas approved these changes
This looks great, thanks for the great work @gallettilance! One small nit, but otherwise /lgtm

2020-12-10 21:45 UTC, ankitathomas commented on content/en/docs/Concepts/olm-architecture/operator-registry/building-a-catalog.md
> +The version specifying the `skipRange` will be presented as a direct (one hop) update to
nit: This should be olm.skipRange

2020-12-10 21:50 UTC, dinhxuanvu requested changes
Just a few comments.

2020-12-10 21:50 UTC, dinhxuanvu commented on content/en/docs/Concepts/olm-architecture/operator-registry/building-a-catalog.md
> +specific versions is possible with this update graph by modifying the `startingCsv` field
`startingCSV`

2020-12-10 21:50 UTC, dinhxuanvu commented on content/en/docs/Concepts/olm-architecture/operator-registry/building-a-catalog.md
> +      olm.skiprange: <1.0.3
`skipRange`

2020-12-10 21:50 UTC, dinhxuanvu commented on content/en/docs/Concepts/olm-architecture/operator-registry/building-a-catalog.md
> +the `startingCsv` field of the subscription is not possible when using skiprange only.
startingCSV

2020-12-10 21:50 UTC, dinhxuanvu commented on content/en/docs/Concepts/olm-architecture/operator-registry/building-a-catalog.md
> +OLM also allows you to specify updates through version ranges in your CSV.
Should mention specifically the semver version range and link to semver version range spec page.

2020-12-10 21:50 UTC, dinhxuanvu commented on content/en/docs/Concepts/olm-architecture/operator-registry/building-a-catalog.md
> +      olm.skiprange: <1.0.3
We usually avoid the example of unbounded range like this. You should use a bounded range example such as `>1.0.0 <1.1.0`.

2020-12-10 21:50 UTC, dinhxuanvu commented on content/en/docs/Concepts/olm-architecture/operator-registry/building-a-catalog.md
> +The version currently installed must be in the `skiprange` field of a CSV in the new channel.
`skipRange`

2020-12-10 21:50 UTC, dinhxuanvu commented on content/en/docs/Concepts/olm-architecture/operator-registry/building-a-catalog.md
> +## SkipRange
Should add a note/warning here is that CSV will need to specify `version` in order to use `skipRange`. That field is not required at the moment.

2020-12-10 21:52 UTC, exdx commented on content/en/docs/Concepts/olm-architecture/operator-registry/building-a-catalog.md
> +specific versions is possible with this update graph by modifying the `startingCsv` field
should we also specify that the install plan approval setting on the sub should be set to `Manual` to ensure that it stays at that specific version and not auto-updates?

2020-12-10 21:54 UTC, exdx commented
Also, I think this topic is so nuanced it deserves its own page, for example `How to specify an upgrade path for your operator` so we can easily link it to people when they have a question regarding skips/replaces. We could link to that page on the bottom of this page on building a catalog. WDYT?

2020-12-10 22:13 UTC, ankitathomas approved these changes
/lgtm

2020-12-10 22:17 UTC, dinhxuanvu approved these changes
/lgtm

2020-12-11 19:20 UTC, anik120 requested changes
@gallettilance thank you for writing up this document. 
I'm a bit confused about the document though. To begin with, I don't see it naturally fitting into the core tasks section of the site. The way the core task is set up is: "I am a brand new reader of this site and I have no idea of what olm is. I am going to follow these series of documents in the order they are in to learn what olm is about. So I go: 
Package my operator (i.e create my bundle) 
Validate my package   (i.e validate my bundle) 
Make my package part of a catalog (i.e load my bundle into an index) 
List operators available to install (i.e have the index loaded onto a cluster as a Catsrc) 
Install my operator (i.e create subscription) 
Uninstall my operator 
Uninstall olm"
This workflow might not come across right now coz a lot of those docs need to be updated to tell the latest story. 
With that in mind, maybe the best place for this information is in the document that talks about the [manifests](https://olm.operatorframework.io/docs/tasks/packaging-an-operator/), or at the very least, maybe we mention there olm allows for you to create a upgrade graph for your operator versions, explain what upgrade graph means (possible with an example diagram), and then point to a doc (possibly this one verbatim, or a little bit modified) that lives in the [concepts ](https://olm.operatorframework.io/docs/concepts/) section that details out ways to create that update graph? 

/hold

2020-12-14 14:20 UTC, gallettilance commented
waiting on #89

2020-12-15 14:07 UTC, dinhxuanvu approved these changes
/lgtm

2020-12-15 14:36 UTC, dinhxuanvu commented
/hold cancel

2020-12-15 15:11 UTC, merged